"""Agregar campo ultimo_abono_fecha a Cliente

Revision ID: 01aa8506af05
Revises: a506676d3737
Create Date: 2025-10-18 13:16:34.021639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01aa8506af05'
down_revision = 'a506676d3737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_abono_fecha', sa.Date(), nullable=True))

    with op.batch_alter_table('prestamo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frecuencia', sa.String(length=20), nullable=True))
        batch_op.alter_column('saldo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_column('entregado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestamo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entregado', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('saldo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('frecuencia')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('ultimo_abono_fecha')

    # ### end Alembic commands ###
