"""Sincronización completa y agregar ultima_aplicacion_interes

Revision ID: 214ed53e4b8c
Revises: e61e32974c13
Create Date: 2025-10-23 00:26:12.095508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214ed53e4b8c'
down_revision = 'e61e32974c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestamo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_aplicacion_interes', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestamo', schema=None) as batch_op:
        batch_op.drop_column('ultima_aplicacion_interes')

    # ### end Alembic commands ###
