"""Agregar columna saldo en Cliente

Revision ID: 7ee70dcb7cd7
Revises: c23833729668
Create Date: 2025-10-16 05:20:28.169113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee70dcb7cd7'
down_revision = 'c23833729668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('saldo')

    # ### end Alembic commands ###
