"""Agregar columna entradas_caja en Liquidacion

Revision ID: a506676d3737
Revises: 7ee70dcb7cd7
Create Date: 2025-10-16 06:23:33.820020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a506676d3737'
down_revision = '7ee70dcb7cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entradas_caja', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidacion', schema=None) as batch_op:
        batch_op.drop_column('entradas_caja')

    # ### end Alembic commands ###
