"""Base limpia inicial con prestamos_hoy

Revision ID: c23833729668
Revises: 
Create Date: 2025-10-15 23:13:44.658146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23833729668'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prestamos_hoy', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidacion', schema=None) as batch_op:
        batch_op.drop_column('prestamos_hoy')

    # ### end Alembic commands ###
