"""Agregar campo ultima_aplicacion_interes a Prestamo

Revision ID: e61e32974c13
Revises: fe55aeaa9ecb
Create Date: 2025-10-22 23:11:32.006806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61e32974c13'
down_revision = 'fe55aeaa9ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestamo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_aplicacion_interes', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestamo', schema=None) as batch_op:
        batch_op.drop_column('ultima_aplicacion_interes')

    # ### end Alembic commands ###
